### ISSUE TITLE
[doc] Table of contents cut out of the page

### ISSUE THREAD

**Issue by evandrocoan** [SublimeText/sublime_lib#102]
![image](https://user-images.githubusercontent.com/5332158/51432627-cd936c00-1c21-11e9-9b9b-a8163f6d553f.png)

**Comment by Thom1729** [comment]
@FichteFoll I fixed this in https://github.com/SublimeText/sublime_lib/commit/875179993e5afe21ec0d0e95c8cb7cf89a909c20, but accidentally pushed to master instead of a new branch. If there are any problems with it, I can back it out and turn it into a proper PR.

The new implementation uses `position: sticky` instead of `position: fixed`. It should work better for small viewport sizes. In ancient browsers (i.e. IE), it should degrade gracefully (the table of contents won't move).

**Comment by FichteFoll** [comment]
No problems. I'm most likely too lazy to pull and build documentation changes anyway which I would have to do in order to test style changes like this properly. `position: sticky; max-height: 100vh;` sounds like a good solution.

The only problem is that the vertical scrollbar causes a horizontal scrollbar to appear as well as the content doesn't fit horizontally anymore.

![2019-01-25_20-14-46](https://user-images.githubusercontent.com/931051/51767545-08901680-20de-11e9-8333-c31a5687f98f.png)

**Comment by evandrocoan** [comment]
> The only problem is that the vertical scrollbar causes a horizontal scrollbar to appear as well as the content doesn't fit horizontally anymore.

I did not got a horizontal scrollbar here. Even if it did, it should be fine, Sublime Text also does one when things do not fit.
![image](https://user-images.githubusercontent.com/5332158/51772000-fb6d2a80-20d1-11e9-9e80-f6ac1288f1e9.png) ![image](https://user-images.githubusercontent.com/5332158/51771961-e09ab600-20d1-11e9-86c3-a33f39f460c2.png)

**Comment by FichteFoll** [comment]
The problem is that the horizontal bar only occurs when the vertical one is visible. That's not good UX.

**Comment by Thom1729** [comment]
I couldn't reproduce, but I changed the `overflow` to an `overflow-y`. That should fix it.

**Comment by FichteFoll** [comment]
It doesn't, actually. I could make the fix work with `word-wrap: break-word`, but that's not optimal. Instead, I added some padding for the width of the scrollbar. https://github.com/SublimeText/sublime_lib/commit/340fc36a2cb6068d3b9a80d52562f801daa695a2
