### ISSUE TITLE
1.3 Release

### ISSUE THREAD

**Issue by Thom1729** [SublimeText/sublime_lib#107]
Since 1.2:

- MyPy type checking (only the Sublime API so far).
- New `Panel` class.
- More flexibility when passing flags to `show_selection_panel`.
- New methods of ResourcePath: `add_suffix`, `remove_suffix`, `relative_to`, `copy`, `copytree`.
- Explicitly handle errors in `encodings`.
- Fixed the docs overflow issue.

I'm still working on adding more type checking and on the async utilities. I think that these can wait for a future release.

Is there other low-hanging fruit we should look at, or is it a good time to release 1.3? I'll have to go through and make sure that the documentation is ready (declaring `versionadded` and such).

**Comment by FichteFoll** [comment]
I still haven't looked at the async stuff. Can't really justify getting myself into that while having a lot of other more important tasks.
No idea where exactly you want to go with type checking.

I'm not aware of any modifications we'd need, since I barely use the lib, though just today I would have liked a representation of `ResourcePath` where the `Packages` root was replaced with `${packages}` for the `edit_settings` command (also works for `open_file`). Not sure how a reasonable API could look for that.

**Comment by Thom1729** [comment]
> I would have liked a representation of ResourcePath where the Packages root was replaced with ${packages} for the edit_settings command (also works for open_file). Not sure how a reasonable API could look for that.

Seems reasonable:

```python
def for_open_file_command(self):
    return '/'.join(('${packages}',) + my_path.relative_to('Packages'))
```

Any ideas for the name?

**Comment by Thom1729** [comment]
Agreed, especially because it's such a niche feature. I'll probably update the docs later today. If either of us has a better name idea, it should be easy to add the method before 1.3. If not, considering how hard it is to rename things, we might punt it to the next release.

**Comment by FichteFoll** [comment]
1.3 has been released on 2019-02-04.
