### ISSUE TITLE
Output Panel Abstraction

### ISSUE THREAD

**Issue by Thom1729** [SublimeText/sublime_lib#3]
The PackageDev implementation is here: https://github.com/SublimeText/PackageDev/blob/d22a77646b3b3e9ab06f81ab0b6037ea17ef2380/plugins_/lib/sublime_lib/view/output_panel.py

**Comment by Thom1729** [comment]
Comments on the existing implementation:

- Adding `flush` (a no-op) would make it file-like.
- What about renaming `write_line` to `print`?

**Comment by FichteFoll** [comment]
- +1 for `flush`
- Technically, since the class is file-like, `print(file=output_panel)` could be used, but I'm not sure whether that is clear enough. If we think of it as an abstraction over a file (as it is file-like), then we should perhaps just scrape `write_line` completely and have users resort to their usual methods of adding newlines to a file or some other buffer.

**Comment by FichteFoll** [comment]
We should also think of how a `LogHandler` targetting an output panel should be implemented for use with the `logging` stdlib.

**Comment by Thom1729** [comment]
It should work with `StreamHandler`, at the least.

On a related note, it might be useful to implement a simple `ViewStream` that implements `write` and `flush` and have the output view subclass that. That would be handy for anyone who wants to build up a view in a file-like manner.
