### ISSUE TITLE
Generate also a single API documentation page like Sublime Text API page

### ISSUE THREAD

**Issue by evandrocoan** [SublimeText/sublime_lib#74]
Currently you need to browse through all submodules pages:
![image](https://user-images.githubusercontent.com/5332158/49539872-c7397280-f8b5-11e8-8e1b-059b097259d2.png)

But, It would be nice if I can access a single page with everything, like the Sublime API page: https://www.sublimetext.com/docs/3/api_reference.html

**Comment by FichteFoll** [comment]
Adding this here since it's most relevant:

Many functions, classes and methods provided require the API to have loaded. Thus, it makes sense to mention this on the front page instead of every exported function or class.


Furthermore, we export most of the things that are stored in submodules from the main module and those locations should be the ones documented.

**Comment by FichteFoll** [comment]
Done via #77.

**Comment by FichteFoll** [comment]
Well, except for this, I guess?

>Many functions, classes and methods provided require the API to have loaded. Thus, it makes sense to mention this on the front page instead of every exported function or class.
